### PR TITLE
A quick rewrite of outline based on discussion with @joeyklee

### PR DESCRIPTION
**Pull request by shiffman**
I just met with @joeyklee who has made many wonderful tutorial projects in the areas I'd like to cover and we are now discussing collaborating on the materials. 

I love the idea of this playlist as a series of 3 start to finish project tutorials. The same concepts would be covered but through the lens of the specific sample projects.

### CODE REVIEW

**Comment by shiffman** [comment]
I'm going to go ahead and merge this, but @joeyklee if you have thoughts or comments feel free to open issues, make a pull request, or we can discuss more in person etc!

**Comment by joeyklee** [comment]
Thanks Dan! I will collect some links and resources to projects that could be of interest for Project 1 as well as potential other ideas that could be useful for the other Projects / Chapters of the series. 

I will also go through and do better documentation - adding comments to code and adding screenshots and instructions - that might be helpful to have in tandem with the videos. 

Also adding references to other projects etc.

**Comment by joeyklee** [comment]
@shiffman - one thought also we didn't entertain yet is to use some charting libraries. Maybe this is worth also integrating regarding the more "canonical" chart making:

e.g.:
+ https://naver.github.io/billboard.js/
+ https://eventbrite.github.io/britecharts/
+ https://www.chartjs.org/

They all kind of do the same thing ==> data in == >chart out. I suppose it wouldn't be terrible to just choose one we think reads the best. 🤔

**Comment by shiffman** [comment]
Yes, interesting! This could pair nicely with a short "tabular data" project loading a CSV. It might even be interesting to compare contrast using a charting library vs. drawing a chart "manually" with p5.js. We can move some of these conversations into separate issue threads if you like!

**Comment by joeyklee** [comment]
@shiffman  - yep! Let's move them to separate issues and open/close them accordingly :) Thanks!

**Pull request merged**
